# Generated by Django 3.1.3 on 2020-12-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='isShareable',
            field=models.BooleanField(default=True),
        ),
    ]
