# Generated by Django 3.1.3 on 2020-12-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20201203_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
