# Generated by Django 3.1.3 on 2020-12-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20201203_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='calendarId',
            new_name='calendar',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='accountId',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='calendarId',
            new_name='calendar',
        ),
    ]
