# Generated by Django 3.1.3 on 2020-12-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20201204_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
